[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default.rpc_endpoints]
base = "${BASE_RPC_URL}"
base-sepolia = "${BASE_SEPOLIA_RPC}"

[profile.default.etherscan]
base = { key = "${BASESCAN_API_KEY}" }
base-sepolia = { key = "${BASESCAN_API_KEY}" }

# Solidity compiler settings
[profile.default.solc]
version = "0.8.20"
optimizer = true
optimizer_runs = 200

# Gas settings
gas_reports = ["*"]
gas_limit = 30000000
